- name: Set up a Rust toolchain
  uses: hecrj/setup-rust-action@v1.3.3


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  - name: Set up a Rust toolchain
    uses: hecrj/setup-rust-action@v1.3.3
    with:
      # The toolchain name, such as stable, nightly, or 1.8.0
      rust-version: # optional, default is stable
      # The toolchain components to install, comma-separated
      components: # optional, default is 
      # The toolchain targets to add, comma-separated
      targets: # optional, default is 
